# Generated by Django 6.0.4 on 2026-04-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=200)),
                ('Tipo', models.CharField(choices=[('Fundacion', 'Fundacion'), ('Junta de Vecinos', 'Junta de Vecinos'), ('Club Deportivo', 'Club Deportivo')], max_length=20)),
                ('contacto', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
