# Generated by Django 6.0.4 on 2026-04-15 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizacion',
            old_name='contacto',
            new_name='Contacto',
        ),
        migrations.RenameField(
            model_name='organizacion',
            old_name='descripcion',
            new_name='Descripcion',
        ),
        migrations.RenameField(
            model_name='organizacion',
            old_name='direccion',
            new_name='Direccion',
        ),
        migrations.RenameField(
            model_name='organizacion',
            old_name='nombre',
            new_name='Nombre',
        ),
    ]
